osx_image: xcode8.2
language: objective-c
script:
- set -o pipefail && xcodebuild test -workspace Example/DominoKit.xcworkspace -scheme DominoKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
